config/routes.rb
Adw::Application.routes.draw do

  devise_for :admins

  namespace :admin do  
        
    resources :pages      
        
     get "destroy_photo/:id", :to => "photos#destroy_photo", :as => "destroy_photo"
     post "destroy_photo_on_cloudinary/:public_id", :to => "photos#destroy_on_cloudinary", :as => "destroy_on_cloudinary"
     
     post "produits-activate-photo", :to => "produits#activate_photo"
     
       
     resources :photos, :produits    
     resources :activities, :promos, :focus,  :only => [:edit, :update]
     
     get "/", :to => "home#index", :as => "index"
     
     post "promos-activate-photo", :to => "promos#activate_photo"       

     post "focus-upload-to-link-with", :to => "focus#upload_to_link_with", :as => "upload_to_link"       
     post "focus-activate-photo", :to => "focus#activate_photo"       
     
     
  end 
  
  
  get "promo", :to => "home#promo", :as => "promo"
  get "focus", :to => "home#focus", :as => "focus"
  get "produits", :to => "home#produits", :as => "produit"
  get "services", :to => "home#services", :as => "service"
  get "notre-activite", :to => "home#activities", :as => "activity"
  get "plan-horaires", :to => "home#map", :as => "map"
  get "contact", :to => "home#contact", :as => "contact"
      

   root :to => 'home#index'

end

app/views/admin/pages/_form.html.erb
<%= simple_form_for(@page, url: admin_pages_path, method: "post") do |f| %>
  <%= f.error_notification %>

  <ul data-role="listview" data-divider-theme="c" data-theme="c" data-inset="true">
	  <li class="fieldcontain">
	  	<%= f.input :titre_menu, label: "Elément du menu" %>
	  </li>
	  <li class="fieldcontain">	
	    <%= f.input :titre, label: "Titre de la page" %>
	  </li>
	  <li class="fieldcontain">
		<label for="flip-mini" class="string optional control-label ui-input-text">Ajouter une photo ?</label>
		<select name="flip-mini" id="add-photo-page" data-role="slider" data-mini="true" data-page="<%= @page %>" >
			<option value=off <%= 'selected="true"' unless @page.photo %> >Oui</option>
			<option value=on <%= 'selected="true"' if @page.photo %>  >Non</option>
		</select>	
	    <%= f.input :photo, :as => "hidden" %>
	  </li>
	  <li class="fieldcontain">		
		<%= f.input :description %>
      </li>	
	  <li class="fieldcontain">	
        <%= f.button :submit, "data-inline" => "true", "data-theme" => "a"  %>
		<%= f.button :submit, "annuler", :type => "reset" , "data-inline" => "true"  %>
      </li>
<% end %>

<script>
	// open dialog window
	$('#add-photo-page').on('change', function() {
		//$(this).slider({ disabled: true });
	  	if($(this).val() != 'off') 
		{
			$('#mypanel_gallery').panel('open');
		}
	});		
</script>

app/views/admin/pages/_form_edit.html.erb
<%= simple_form_for(@page, url: admin_page_path, method: "put") do |f| %>
  <%= f.error_notification %>

  <ul data-role="listview" data-divider-theme="c" data-theme="c" data-inset="true">
	  <li class="fieldcontain">
	  	<%= f.input :titre_menu, label: "Elément du menu" %>
	  </li>
	  <li class="fieldcontain">	
	    <%= f.input :titre, label: "Titre de la page" %>
	  </li>
	  <li class="fieldcontain">
		<label for="flip-mini">Ajouter une photo ?:</label>
		<select name="flip-mini" id="add-photo-page" data-role="slider" data-mini="true" data-page="<%= @page %>" >
			<option value=off <%= 'selected="true"' unless @page.photo %> >Non</option>
			<option value=on <%= 'selected="true"' if @page.photo %>  >Oui</option>
		</select>	
	    <%= f.input :photo, :as => "hidden" %>
	  </li>
	  <li class="fieldcontain">		
		<%= f.input :description %>
      </li>	
	  <li class="fieldcontain">	
        <%= f.button :submit, "data-inline" => "true", "data-theme" => "a"  %>
		<%= f.button :submit, "annuler", :type => "reset" , "data-inline" => "true"  %>
      </li>
<% end %>

<script>
	// open dialog window
	$('#add-photo-page').on('change', function() {
		//$(this).slider({ disabled: true });
	  	if($(this).val() != 'off') 
		{
			$('#mypanel_gallery').panel('open');
		}
	});		
</script>

app/views/admin/pages/edit.html.erb
<h1>Edition de la page</h1>

<%= render 'form_edit' %>

<%= link_to 'Show', admin_path(@page) %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<h1>Liste des pages</h1>
<table data-role="table" id="table-column-toggle" data-mode="columntoggle" class="ui-responsive table-stroke ui-body-d table-stripe" data-column-btn-text="Afficher +">
  <thead>
    <tr class="ui-bar-d">
      <th data-priority="1">Elément du menu</th>
      <th data-priority="1">Titre de la page</th>
      <th data-priority="1" colspan="3">Image</th>
    </tr>
  </thead>
  <tbody>
		<% @pages.each do |page| %>
		<tr>
	    	<td><%= page.titre_menu %></td>
		    <td><%= page.titre %></td>
		    <td><%= page.photo %></td>
		    <td data-priority="2"><%= link_to "Modifier", edit_admin_page_path(page.id), "data-role"=>"button", "data-icon" => "edit", "data-iconpos" => "notext", :class => "ui-icon-alt" %></td>
	      <td data-priority="2"><%= link_to "Supprimer", admin_page_path(page.id), method: :delete, data: { confirm: 'Etes vous sur ?' }, "data-role"=>"button", "data-icon" => "delete" , "data-iconpos" => "notext", :class => "ui-icon-alt" %></td>
	<% end %>
  </tbody>
</table>

<br />

<%= link_to 'Nouvelle Page', new_admin_page_path, "data-role"=>"button" %>

app/views/admin/pages/new.html.erb
<h1>Nouvelle page</h1>
<!-- Photos Gallery -->
<%= render 'layouts/panel_photos_gallery' %>
<%= render 'form' %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titre menu:</b>
  <%= @page.titre_menu %>
</p>

<p>
  <b>Titre:</b>
  <%= @page.titre %>
</p>

<p>
  <b>Photo:</b>
  <%= @page.photo %>
</p>

<p>
  <b>Description:</b>
  <%= @page.description %>
</p>


<%= link_to 'Edit', edit_admin_page_path(@page) %> |
<%= link_to 'Back', admin_pages_path %>