config/routes.rb
Adw::Application.routes.draw do

  devise_for :admins

  namespace :admin do  
        
    resources :pages      
        
     get "destroy_photo/:id", :to => "photos#destroy_photo", :as => "destroy_photo"
     post "destroy_photo_on_cloudinary/:public_id", :to => "photos#destroy_on_cloudinary", :as => "destroy_on_cloudinary"
     
     post "produits-activate-photo", :to => "produits#activate_photo"
     
       
     resources :photos, :produits    
     resources :activities, :promos, :focus,  :only => [:edit, :update]
     
     get "/", :to => "home#index", :as => "index"
     
     post "promos-activate-photo", :to => "promos#activate_photo"       

     post "focus-upload-to-link-with", :to => "focus#upload_to_link_with", :as => "upload_to_link"       
     post "focus-activate-photo", :to => "focus#activate_photo"       
     
     
  end 
  
  
  get "promo", :to => "home#promo", :as => "promo"
  get "focus", :to => "home#focus", :as => "focus"
  get "produits", :to => "home#produits", :as => "produit"
  get "services", :to => "home#services", :as => "service"
  get "notre-activite", :to => "home#activities", :as => "activity"
  get "plan-horaires", :to => "home#map", :as => "map"
  get "contact", :to => "home#contact", :as => "contact"
      

   root :to => 'home#index'

end

app/models/produit.rb
class Produit < ActiveRecord::Base
  attr_accessible :description, :prix, :titre, :photo_active, :type_of_produit
  
  
  validates :description, length: { minimum:  10 }
  validates :titre, length: { minimum: 3 }
  validates :type_of_produit, :presence => true
  has_and_belongs_to_many :photos, uniq: true
  
end

app/controllers/admin/produits_controller.rb
# encoding: utf-8
class Admin::ProduitsController < ApplicationController
  
  before_filter :authenticate_admin!, except: :show 
  before_filter :no_param_after_destroy, only: :show 
  
  layout 'admin', except: :show
  
  # GET /produits
  # GET /produits.json
  def index
    @produits = Produit.where(:type_of_produit => "Produit").limit(15).order("created_at DESC")
    @services = Produit.where(:type_of_produit => "Service").limit(15).order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produits }
    end
  end

  # GET /produits/1
  # GET /produits/1.json
  def show
    @produit = Produit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produit }
    end
  end

  # GET /produits/new
  # GET /produits/new.json
  def new
    @produit = Produit.new
    @photos = Photo.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produit }
    end
  end

  # GET /produits/1/edit
  def edit
    @produit = Produit.find(params[:id])
    @photos = Photo.all
  end

  # POST /produits
  # POST /produits.json
  def create
    @produit = Produit.new(params[:produit])
    @photo = Photo.find_by_id(params[:photo_attached].to_i)
    respond_to do |format|
      if @produit.save
        @produit.photos << @photo if @photo
        format.html { redirect_to  admin_produits_path , notice: 'Le Produit ou le service a bien été créé.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /produits/1
  # PUT /produits/1.json
  def update
    @produit = Produit.find(params[:id])
    @photo = Photo.find_by_id(params[:photo_attached].to_i)
    
    respond_to do |format|
      if @produit.update_attributes(params[:produit])
        if @photo 
          @produit.photos.clear
          @produit.photos << @photo
        end  
        format.html { redirect_to admin_produits_path, notice: 'Le Produit ou le service a bien été mis à jour.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /produits/1
  # DELETE /produits/1.json
  def destroy
    @produit = Produit.find(params[:id])
    if !@produit.photos.empty?
      @produit.photos.clear
    end  
    @produit.destroy

    respond_to do |format|
      format.html { redirect_to admin_produits_url }
      format.json { head :no_content }
    end
  end
  
  ###############################
  #                             #
  #   Choose a photo to link    #
  #                             #
  ###############################
  
  
  def activate_photo
    produit = Produit.find(params[:produit_id])
    if params[:photo_active]
      photo_activate = true
    else 
      photo_activate = false
    end    
    respond_to do |format|
      if !produit.update_attributes(:photo_active => photo_activate)
        format.js
      else 
        format.js { render :nothing => true }   
      end 
    end
  end
  
  
  
  private 
  
  def no_param_after_destroy 
    if Produit.find_by_id(params[:id]) == nil
      redirect_to admin_produits_path
    end  
  end
  
  
end

app/helpers/admin/produits_helper.rb
module Admin::ProduitsHelper
end

app/views/produits/new.html.erb
<form class="add-photo">
    <ul data-role="listview" data-divider-theme="e" data-inset="true">
        <li data-role="list-divider">
			Ajouter une photo à mon produit 
		</li>	
		<li class="fieldcontain">	
			<select name="flip-mini" id="add-photo-produit" data-role="slider" data-mini="true" data-promo="<%= @produit.id %>" >
				<option value=off <%= 'selected="true"' unless @produit.photo_active %> >Off</option>
				<option value=on <%= 'selected="true"' if @produit.photo_active %>  >On</option>
			</select>
        </li>
    </ul>
</form>
	
<ul data-role="listview" data-theme="c" data-divider-theme="c" data-inset="true" class="photo-actived <%='photo-desactived' unless @produit.photo_active %>">
	<li data-role="list-divider">
		&nbsp;
	</li>
	<li>
		<a href="#mypanel">Depuis l'album</a>
	</li>	
	
	<!-- *********** Or upload a new photo ************* -->
	
	
	<!-- Progress bar -->

	<script id="template-upload" type="text/x-tmpl">
		<p class="upload-message">Merci de patienter pendant le traitement de votre photo ...</p>
		<div class="upload">
			<div class="progress"><div class="bar" style="width: 0%"></div></div>
		</div>
	</script>


	<!-- Photo uploading  -->
	<%= simple_form_for Photo.new, url: admin_upload_to_link_path, html: {:id => "new-photo"} do |f| %>
		<li class="fieldcontain"><%= f.error_notification %></li>
		<li class="fieldcontain">
				<%= f.input :image, label: false, input_html: {"name" => "photo[image]"} %>
			</li>	
	<% end %>
	
	
	<!-- ********************************************** -->
	<li class="photo-actived <%= 'photo-desactived' unless @produit.photo_active %>"  id="thumb-selected">
		<% if !@produit.photos.empty?
			@produit.photos.each do |p| %>
				<%= link_to image_tag(p.image_url(:thumb_list), :alt => "", :class => "thumb-selected", :id => p.id), admin_photo_path(p.id) %>
			<% end %>
		<% end %>
	</li>
</ul>		

	<!-- **************  Ajout du produit  ************** -->

	<%= render 'form' %>

	<%= link_to 'Back', produits_path %>
	
	<%= javascript_include_tag('produits.js') %>