config/routes.rb
Adw::Application.routes.draw do

  devise_for :admins

  namespace :admin do  
        
    resources :pages      
        
     get "destroy_photo/:id", :to => "photos#destroy_photo", :as => "destroy_photo"
     post "destroy_photo_on_cloudinary/:public_id", :to => "photos#destroy_on_cloudinary", :as => "destroy_on_cloudinary"
     
     post "produits-activate-photo", :to => "produits#activate_photo"
     
       
     resources :photos, :produits    
     resources :activities, :promos, :focus,  :only => [:edit, :update]
     
     get "/", :to => "home#index", :as => "index"
     
     post "promos-activate-photo", :to => "promos#activate_photo"       

     post "focus-upload-to-link-with", :to => "focus#upload_to_link_with", :as => "upload_to_link"       
     post "focus-activate-photo", :to => "focus#activate_photo"       
     
     
  end 
  
  
  get "promo", :to => "home#promo", :as => "promo"
  get "focus", :to => "home#focus", :as => "focus"
  get "produits", :to => "home#produits", :as => "produit"
  get "services", :to => "home#services", :as => "service"
  get "notre-activite", :to => "home#activities", :as => "activity"
  get "plan-horaires", :to => "home#map", :as => "map"
  get "contact", :to => "home#contact", :as => "contact"
      

   root :to => 'home#index'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="ui-bar ui-bar-<%= name == :notice ? "e" : "a" %>">
       <%= content_tag :p, msg, :id => "flash_#{name}" %>
		<!-- 
	   <a href="#" data-role="button" data-icon="delete" data-inline="true" data-iconpos="notext" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" title="Dismiss" class="ui-btn ui-btn-up-e ui-shadow ui-btn-corner-all ui-btn-inline ui-btn-icon-notext">

		  <span class="ui-btn-inner ui-btn-corner-all">
		  <span class="ui-btn-text">Dismiss</span>
		  <span class="ui-icon ui-icon-delete ui-icon-shadow"/>
		  </span> -->
	   </a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_panel.html.erb
<div data-role="panel" data-display="overlay" id="mypanel" style="background:#333;">
	<div >
		<a href="#my-header" data-rel="close" data-role="button">Fermer</a>
		<br>
		<br>
		<% if @photos %> 
			<% @photos.each do |photo| %>
						<%= image_tag photo.image_url(:thumb_list), :alt => "" %>
			<% end %>
		<% end %>	
	</div>
</div><!-- /panel -->

app/views/layouts/_panel_admin_nav.html.erb
<div data-role="panel" data-display="overlay" id="mypanel_admin_nav" style="background:#333;">
	<ul data-role="listview" data-theme="c" class="ui-icon-alt">
		<li data-role="divider">Menu</li>
		<li><%= link_to "Promo&nbsp;#{promo_actived?(@promo)}".html_safe, edit_admin_promo_path(@promo), "data-ajax" => false %></li>
		<li><%= link_to "Focus&nbsp;#{focus_actived?(@focus)}".html_safe, edit_admin_focu_path(@focus), "data-ajax" => false %></li>
		<li><%= link_to "Photos".html_safe, admin_photos_path, "data-ajax" => "false"  %></li>
		<li><%= link_to "Produits & Services".html_safe, admin_produits_path %></li>
		<li><%= link_to "Pages", admin_pages_path %></li>
	</ul>
</div><!-- /panel -->

app/views/layouts/_panel_nav.html.erb
<div data-role="panel" data-display="overlay" id="mypanel_nav" data-theme="a">
	<ul data-role="listview" style="margin-bottom:0px" data-theme="c" data-divider-theme="a" class="ui-icon-alt">
		<li data-role="divider">Menu</li>
		<li><%= link_to image_tag("home-16x16.png", :class => "ui-li-icon")+"&nbsp;Accueil".html_safe,root_path,  "data-transition" => "flip" %></li>
		<% if @promo.active %>
			<li><%= link_to image_tag("home-16x16.png")+"&nbsp;Promo".html_safe,promo_path,  "data-transition" => "flip" %></li>
		<% end %>	
		<% if @focus.active %>
			<li><%= link_to image_tag("home-16x16.png", :class => "ui-li-icon")+"&nbsp;#{@focus.type_of_focus}".html_safe,focus_path, "data-transition" => "flip", "data-prefetch" => "" %></li>
		<% end %>
		<% unless @produits.empty? %>
			<li><%= link_to image_tag("home-16x16.png", :class => "ui-li-icon")+"&nbsp;Produits".html_safe,produit_path, "data-transition" => "flip", "data-prefetch" => "" %>
			</li>
		<% end %>
		<% unless @services.empty? %>	
			<li><%= link_to image_tag("home-16x16.png", :class => "ui-li-icon")+"&nbsp;Services".html_safe,service_path, "data-transition" => "flip", "data-prefetch" => "" %>
			</li>
		<% end %>	
		<li><%= link_to image_tag("home-16x16.png", :class => "ui-li-icon")+"&nbsp;Mieux nous connaître".html_safe,activity_path, "data-transition" => "flip" %></li>
		<li><%= link_to image_tag("home-16x16.png", :class => "ui-li-icon")+"&nbsp;Plan & Horaires".html_safe,map_path, "data-transition" => "flip", "data-prefetch" => "" %></li>
		<li><%= link_to image_tag("home-16x16.png", :class => "ui-li-icon")+"&nbsp;Contact".html_safe,contact_path, "data-transition" => "flip", "data-prefetch" => "" %></li>
	</ul>
	<!-- /navigation -->
</div>

app/views/layouts/_panel_photos_gallery.html.erb
<div data-role="panel" data-display="overlay" id="mypanel_gallery" data-theme="a" data-position="right" data-swipe-close="false" data-dismissible="false">
	<h1>Choisir dans ma galerie</h1>
	<% if @photos %> 
		<% @photos.each do |photo| %>
			<%= image_tag(photo.image_url, :alt => "mes photos", :class => "choose_from_album", :id => photo.id, :width => "60px", :height => "60px", :crop => :scale, :name => photo.image_url) %>
		<% end %>
	<% end %>
	<br>
	<%= link_to "annuler", new_admin_page_path, "data-role" => "button", :id => "cancel-add-photo-to-page", "data-mini" => true, "data-theme" => "c" %>
</div>	

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artisans du web | Mobile</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag  "admin/application", :media => "all" %>

  <%= javascript_include_tag "application" %>	

  <%= csrf_meta_tags %>
</head>
	<body>
	
	<div data-role="page" class="mypage">
		
		<!-- Menu in Panel -->
		<%= render "/layouts/panel_admin_nav" %>
		
		<!-- header -->
		<div data-role="header" class="page-header" data-theme="c">
	    	<a href="index.html" data-icon="arrow-l" data-iconpos="notext" data-direction="reverse" data-rel="back" data-role="button" class="ui-btn-left">Back</a>    			
	    	<h1><%= @title %></h1>
			<a href="#mypanel_admin_nav" data-role="button"  class="ui-btn-right"> Menu</a>	
					<!--<a href="/" data-icon="home" data-iconpos="notext" rel="external" class="ui-btn-right">Home</a>-->
		</div>
	    <!--/header -->

		<!-- main content -->
	    <div data-role="content" class="main-content">
			<div data-role="content-padd">
				<%= render "layouts/messages" %>
				<%= yield %>
				<%= debug(params) if Rails.env.development? %>
			</div><!-- end content-padd -->
		</div><!-- end content -->
	</div><!-- end page -->	
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artisans du web | Mobile</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- For iphone -->	
   <link rel="apple-touch-icon" href="/adw-icone.png">
  
  <%= stylesheet_link_tag  "application", :media => "all" %>
  <%= javascript_include_tag "application" %>	

  <%= csrf_meta_tags %>
</head>
	<body>
		<div data-role="page" data-theme="c">
			
			<!-- Menu in Panel -->
			<%= render "/layouts/panel_nav" %>	
			
		<!-- header -->
		<div data-role="header" class="page-header" data-theme="c">
	    	<a href="index.html" data-icon="arrow-l" data-iconpos="notext" data-direction="reverse" data-rel="back" data-role="button" class="ui-btn-left">Back</a>    			
	    	<h1><%= @title %></h1>
			<a href="#mypanel_nav" data-role="button"  class="ui-btn-right"> Menu</a>	
					<!--<a href="/" data-icon="home" data-iconpos="notext" rel="external" class="ui-btn-right">Home</a>-->
		</div>
	    <!--/header -->
	
		<!-- main content -->
	    <div data-role="content" id="bck-content">
			<div data-role="content-padd" class="main-content">
				<%= render 'layouts/messages' %>
				 <% if request.fullpath == "/"%>
					<!-- banner & title -->
					<div class="bannerContainer">
						<!-- <%= image_tag "2.jpg", :class => "banner" %> -->	
					</div>
					<h2 class="pageTitle"><span><%= @title %></span></h2>
					<!-- /banner & title -->
				<% end %>
				<%= yield %>
			</div><!-- end content-padd -->
		</div><!-- end content -->	 
		
		<!-- footer -->
		<div data-role="footer" data-theme="c" data-position="fixed">
			<div data-role="navbar" class="custom-icons">
				<ul>
					<li><a href="http://bit.ly/yx2mXZ" id="run" data-icon="arrow-u">Nous trouver</a></li>
					<li><a href="tel:18005551234" id="phone2" data-icon="arrow-u">Contact</a></li>
					<li><a href="twitter.html" id="twitter" data-icon="arrow-u" data-ajax="false">Tweets</a></li>
					<li>
						<%= link_to "Admin".html_safe, admin_index_path, "data-ajax" => false, "data-icon" => "arrow-u"%>
					</li>
				</ul>
			</div>
		</div>
		<!-- /footer -->
	</div><!-- end page -->	
</body>
</html>